// Section: bibliography
//
// Edit this file to modify just this section. Content is LaTeX-flavored
// strings consumed by scripts/build.tsx (LaTeX → PDF, pandoc → HTML).

export const bibliographyLines: readonly string[] = [
  "\\begin{thebibliography}{20}",
  "",
  "\\bibitem[Albantakis et~al.(2023)]{albantakis2023}",
  "Albantakis, L., Barbosa, L., Findlay, G., et al. (2023).",
  "\\newblock Integrated information theory (IIT) 4.0: Formulating the properties of phenomenal existence in physical terms.",
  "\\newblock \\emph{PLOS Computational Biology}.",
  "",
  "\\bibitem[Chalmers(1995)]{chalmers1995}",
  "Chalmers, D. J. (1995).",
  "\\newblock Facing up to the problem of consciousness.",
  "\\newblock \\emph{Journal of Consciousness Studies}, 2(3), 200--219.",
  "",
  "\\bibitem[Conant and Ashby(1970)]{conantashby1970}",
  "Conant, R. C. and Ashby, W. R. (1970).",
  "\\newblock Every good regulator of a system must be a model of that system.",
  "\\newblock \\emph{International Journal of Systems Science}, 1(2), 89--97.",
  "",
  "\\bibitem[Csikszentmihalyi(1990)]{flow1990}",
  "Csikszentmihalyi, M. (1990).",
  "\\newblock \\emph{Flow: The Psychology of Optimal Experience}.",
  "\\newblock Harper \\& Row.",
  "",
  "\\bibitem[Friston(2010)]{friston2010}",
  "Friston, K. (2010).",
  "\\newblock The free-energy principle: A unified brain theory?",
  "\\newblock \\emph{Nature Reviews Neuroscience}, 11, 127--138.",
  "",
  "\\bibitem[Hafner et~al.(2020)]{hafner2020}",
  "Hafner, D., Lillicrap, T., Ba, J., and Norouzi, M. (2020).",
  "\\newblock Dream to control: Learning behaviors by latent imagination.",
  "\\newblock \\emph{International Conference on Learning Representations}.",
  "",
  "\\bibitem[Klyubin et~al.(2005)]{klyubin2005}",
  "Klyubin, A. S., Polani, D., and Nehaniv, C. L. (2005).",
  "\\newblock Empowerment: A universal agent-centric measure of control.",
  "\\newblock \\emph{IEEE Congress on Evolutionary Computation}.",
  "",
  "\\bibitem[Nagel(1974)]{nagel1974}",
  "Nagel, T. (1974).",
  "\\newblock What is it like to be a bat?",
  "\\newblock \\emph{The Philosophical Review}, 83(4), 435--450.",
  "",
  "\\bibitem[Oizumi et~al.(2014)]{oizumi2014}",
  "Oizumi, M., Albantakis, L., and Tononi, G. (2014).",
  "\\newblock From information processing to phenomenal consciousness: Integrated information theory 3.0.",
  "\\newblock \\emph{PLOS Computational Biology}, 10(5), e1003588.",
  "",
  "\\bibitem[Oudeyer and Kaplan(2007)]{oudeyer2007}",
  "Oudeyer, P.-Y. and Kaplan, F. (2007).",
  "\\newblock What is intrinsic motivation? A typology of computational approaches.",
  "\\newblock \\emph{Frontiers in Neurorobotics}, 1, 6.",
  "",
  "\\bibitem[Pathak et~al.(2017)]{pathak2017}",
  "Pathak, D., Agrawal, P., Efros, A. A., and Darrell, T. (2017).",
  "\\newblock Curiosity-driven exploration by self-supervised prediction.",
  "\\newblock \\emph{International Conference on Machine Learning Workshops}.",
  "",
  "\\bibitem[Pearl(2009)]{pearl2009}",
  "Pearl, J. (2009).",
  "\\newblock \\emph{Causality: Models, Reasoning and Inference}.",
  "\\newblock Cambridge University Press.",
  "",
  "\\bibitem[Russell(1980)]{russell1980}",
  "Russell, J. A. (1980).",
  "\\newblock A circumplex model of affect.",
  "\\newblock \\emph{Journal of Personality and Social Psychology}, 39(6), 1161--1178.",
  "",
  "\\bibitem[Schmidhuber(1991)]{schmidhuber1991}",
  "Schmidhuber, J. (1991).",
  "\\newblock A possibility for implementing curiosity and boredom in model-building neural controllers.",
  "\\newblock \\emph{Proceedings of the International Conference on Simulation of Adaptive Behavior}.",
  "",
  "\\bibitem[Schrittwieser et~al.(2020)]{muzero2020}",
  "Schrittwieser, J., Antonoglou, I., Hubert, T., et al. (2020).",
  "\\newblock Mastering Atari, Go, chess and shogi by planning with a learned model.",
  "\\newblock \\emph{Nature}, 588, 604--609.",
  "",
  "\\bibitem[Shannon(1948)]{shannon1948}",
  "Shannon, C. E. (1948).",
  "\\newblock A mathematical theory of communication.",
  "\\newblock \\emph{Bell System Technical Journal}, 27, 379--423 and 623--656.",
  "",
  "\\bibitem[Tishby et~al.(1999)]{tishby1999}",
  "Tishby, N., Pereira, F. C., and Bialek, W. (1999).",
  "\\newblock The information bottleneck method.",
  "\\newblock \\emph{37th Annual Allerton Conference on Communication, Control, and Computing}.",
  "",
  "\\bibitem[Tononi(2004)]{tononi2004}",
  "Tononi, G. (2004).",
  "\\newblock An information integration theory of consciousness.",
  "\\newblock \\emph{BMC Neuroscience}, 5, 42.",
  "",
  "\\end{thebibliography}",
] as const;
