// Section: curiosity-creativity-and-intelligence-as-objecti
//
// Edit this file to modify just this section. Content is LaTeX-flavored
// strings consumed by scripts/build.tsx (LaTeX → PDF, pandoc → HTML).

export const curiosityCreativityAndIntelligenceAsObjectiLines: readonly string[] = [
  "\\section{Curiosity, Creativity, and Intelligence as Objective Geometry}",
  "",
  "\\subsection{Curiosity as Epistemic Approach}",
  "",
  "Curiosity is the cleanest first case because proxy error appears immediately \\citep{schmidhuber1991,oudeyer2007,pathak2017}. Novelty alone carries almost no epistemic weight. Noise can generate it. So can distraction, random poking, or damage to the measurement setup; this is the failure mode that \\citet{burda2019} document at scale as the ``noisy-TV'' problem. Uncertainty alone is no better. A system can maximize uncertainty by destroying sensors, randomizing labels, or entering domains where no measurement has traction. That is not curiosity. It is epistemic sabotage.",
  "",
  "The useful form is closer to:",
  "\\begin{equation}",
  "  \\mathrm{Curiosity}(x_t,a) = V^{\\mathrm{epi}}_t(a)\\, H(\\R_{t:t+k}\\mid a)\\, \\Delta \\A_t(a)\\, (1-s_t)\\,\\Safe(x_t,a),",
  "\\end{equation}",
  "where $V^{\\mathrm{epi}}$ is positive epistemic valence, $H(\\R)$ is entropy over plausible future branches, $\\Delta\\A$ is affordance expansion, $s_t$ is self-model salience, and $\\Safe$ is a hard or soft safety term.",
  "",
  "A more direct epistemic-valence term is expected information gain:",
  "\\begin{equation}",
  "  V^{\\mathrm{epi}}(a\\mid h_t)=\\mathbb{E}_{o'\\sim p(o'\\mid h_t,a)}\\left[\\Ent(\\Theta\\mid h_t)-\\Ent(\\Theta\\mid h_t,a,o')\\right],",
  "\\end{equation}",
  "where $\\Theta$ are latent hypotheses and $h_t=e_{\\le t}$ is the event history.",
  "",
  "The operative distinction is precise: uncertainty is welcomed only where it can become traction. Curiosity approaches uncertainty because the world is expected to become more navigable afterward. It is positive valence over uncertainty reduction, not attachment to confusion.",
  "",
  "\\subsection{Creativity as Affordance-Opening Compression}",
  "",
  "Creativity inherits the same proxy trap. Unconstrained creativity metrics collapse into surprise, style, or judge approval. The scientific version is narrower and more useful: a compression that makes new action possible. The closest formal precedent is the compression-progress view of \\citet{schmidhuber2010}, sharpened here by the affordance term.",
  "",
  "Let $M_t$ be the current world model and $M_{t+1}$ the revised model after a trace. Define creative compression:",
  "\\begin{equation}",
  "  C_t = N_t \\cdot \\IG_t \\cdot \\Delta \\A_t \\cdot \\max\\{0,\\MDL(M_t)-\\MDL(M_{t+1})\\}.",
  "\\end{equation}",
  "Here $N_t$ is nontrivial novelty, $\\IG_t$ is information gain, $\\Delta\\A_t$ is affordance expansion, and $\\MDL$ is minimum description length. The compression term inherits its information-theoretic backbone from the information-bottleneck tradition \\citep{tishby1999}. A move is creative when it is new, evidence-contacting, compressive, and enabling.",
  "",
  "In the chemistry demo, the creative act may be small: the agent notices that direct visual pH estimation is unreliable under current lighting, identifies the calibration card, writes a color-normalization routine, segments the pH strip, estimates uncertainty, and reuses the routine on later samples. The value lies precisely in the lack of spectacle. The move is reusable. It changes what future measurements cost.",
  "",
  "\\subsection{Intelligence as Transition-Geometry Alignment}",
  "",
  "Benchmark score is not the invariant. The useful object is alignment between internal transition geometry and environmental transition geometry --- a continuous-systems echo of the good-regulator theorem \\citep{conantashby1970}.",
  "",
  "Let",
  "\\begin{equation}",
  "  D_W(i,j)=d\\left(p(e_{t+1:t+k}\\mid h_i,a_i),\\,p(e_{t+1:t+k}\\mid h_j,a_j)\\right)",
  "\\end{equation}",
  "be a distance matrix over world/event trajectories, and let",
  "\\begin{equation}",
  "  D_Z(i,j)=d\\left(z_{t+1:t+k}^{(i)},z_{t+1:t+k}^{(j)}\\right)",
  "\\end{equation}",
  "be the corresponding internal latent transition geometry. A representational similarity score gives one proxy:",
  "\\begin{equation}",
  "  \\mathcal{I}_{\\mathrm{align}} = \\mathrm{RSA}(D_W,D_Z).",
  "\\end{equation}",
  "This remains insufficient by itself. A passive camera can learn correlations. Intervention must enter the measure:",
  "\\begin{equation}",
  "  \\mathcal{I}_{\\mathrm{sci}} = \\mathcal{I}_{\\mathrm{align}} + \\lambda_1\\,\\mathrm{InterventionSuccess} + \\lambda_2\\,\\mathrm{Transfer} + \\lambda_3\\,\\mathrm{Recovery}.",
  "\\end{equation}",
  "A scientific agent becomes intelligent in the relevant sense when its internal couplings mirror the world's causal couplings well enough to support intervention, transfer, and recovery under perturbation.",
  "",
  "",
  "",
  "\\PaperFigure{objective-shaping}",
  "",
  "",
  "",
  "",
] as const;
