// Section: geometry-before-semantics
//
// Edit this file to modify just this section. Content is LaTeX-flavored
// strings consumed by scripts/build.tsx (LaTeX → PDF, pandoc → HTML).

export const geometryBeforeSemanticsLines: readonly string[] = [
  "\\section{Geometry Before Semantics}",
  "",
  "Experience is often misread as content floating inside a private theater \\citep{nagel1974,chalmers1995}. The cleaner starting point is structural. Experiences, behaviors, and agent trajectories have gradients, couplings, bottlenecks, ranks, attractors, and recovery dynamics. The same vocabulary becomes useful for embodied agents before any strong claim about phenomenality is required.",
  "",
  "The operational argument survives even if the phenomenological interpretation is discarded. Many qualitative categories appear to correspond to measurable structures in trajectory space. Curiosity, boredom, fear, flow \\citep{flow1990}, understanding, and creative insight can be modeled as regions and flows in a geometric space. If the geometry is wrong, the measurements should fail. If the geometry is useful, better agents should become constructible from the measurements.",
  "",
  "One provisional projection for an embodied scientific agent is",
  "\\begin{equation}",
  "  x_t = [v_t, a_t, \\phi_t, r_t, cf_t, s_t, \\iota_t, \\rho_t, \\kappa_t, g_t],",
  "\\end{equation}",
  "where $v_t$ is valence and $a_t$ is arousal \\citep{russell1980}, $\\phi_t$ is integration, $r_t$ is effective rank, $cf_t$ is counterfactual weight, $s_t$ is self-model salience, $\\iota_t$ is inhibition-coefficient state, $\\rho_t$ is self-effect, $\\kappa_t$ is calibration confidence, and $g_t$ is inquiry or goal entropy.",
  "",
  "No claim of completeness is implied by this coordinate choice. The coordinates are provisional projections over a higher-dimensional relational structure. If they fail to distinguish states that matter, the basis must expand. If they collapse distinctions they should preserve, the basis must be replaced. The relevant claim is not coordinate finality; it is that qualitative behavior can become mathematically discussable without being reduced to low-level proxy residue.",
  "",
  "\\subsection{Valence as Gradient Alignment}",
  "",
  "Let $\\V$ be a viability or objective manifold, and let $d(x,\\partial\\V)$ be the distance from the current state to its boundary. If $\\hat{x}_{t:t+k}$ is the predicted trajectory under the current policy, valence can be approximated as alignment with the viability gradient:",
  "\\begin{equation}",
  "  v_t = \\left\\langle \\frac{d\\hat{x}_t}{dt}, \\nabla d(x_t,\\partial\\V) \\right\\rangle.",
  "\\end{equation}",
  "Positive valence corresponds to motion into the viable interior. Negative valence corresponds to motion toward boundary violation. For a scientific agent, the relevant manifold is not only survival. It is epistemic viability: the region where models, tools, calibration, and commitments remain capable of producing trustworthy evidence.",
  "",
  "\\subsection{Arousal as Update Rate}",
  "",
  "Arousal is approximated as belief update rate:",
  "\\begin{equation}",
  "  a_t = \\KL\\big(b_{t+1}\\,\\|\\,b_t\\big),",
  "\\end{equation}",
  "where $b_t$ is the belief state or latent-state distribution \\citep{shannon1948,friston2010}. High arousal marks rapid revision. Low arousal marks proximity to a basin, fixed point, or settled local regime.",
  "",
  "\\subsection{Integration as Irreducibility}",
  "",
  "Integration is the cost of factoring the system \\citep{tononi2004,oizumi2014,albantakis2023}. A tractable proxy is partition prediction loss:",
  "\\begin{equation}",
  "  \\phi_t \\approx \\mathcal{L}_{\\mathrm{partitioned}}(e_{t+1:t+k}\\mid e_{\\le t}) - \\mathcal{L}_{\\mathrm{joint}}(e_{t+1:t+k}\\mid e_{\\le t}).",
  "\\end{equation}",
  "If the joint predictor succeeds where partitioned predictors fail, the system contains coupling that cannot be cleanly decomposed. Complexity alone is insufficient. A pile of unrelated activations can be complicated and still low-$\\phi$.",
  "",
  "\\subsection{Effective Rank as Representational Breadth}",
  "",
  "Let $\\Sigma_t$ be the covariance of latent states over a window. Effective rank is",
  "\\begin{equation}",
  "  r_t = \\exp\\left(-\\sum_i p_i\\log p_i\\right),\\quad p_i = \\frac{\\lambda_i}{\\sum_j \\lambda_j},",
  "\\end{equation}",
  "where $\\lambda_i$ are eigenvalues of $\\Sigma_t$. High rank means many degrees of freedom remain active. Low rank means the representation has collapsed into a narrow subspace.",
  "",
  "\\subsection{Counterfactual Weight as Possible-Future Processing}",
  "",
  "Let $\\R_{t:t+k}$ be the set of imagined rollouts in a learned world model \\citep{ha2018,hafner2020,muzero2020} and $C_{\\mathrm{total}}$ the total compute or representational budget. A simple counterfactual-weight proxy is",
  "\\begin{equation}",
  "  cf_t = \\frac{C(\\R_{t:t+k})}{C_{\\mathrm{total}}}.",
  "\\end{equation}",
  "This is the dimension shared by curiosity, fear, planning, regret, and design. Possibility-space is active. The distinction is made by valence, self-salience, and whether the modeled futures afford traction.",
  "",
  "\\subsection{Self-Effect as Causal Authorship of Observation}",
  "",
  "For observations $O_t$, actions $A_t$, and horizon $\\tau$, define",
  "\\begin{equation}",
  "  \\rho_\\tau = \\frac{\\MI(A_t;O_{t+\\tau}\\mid O_{\\le t})}{\\Ent(O_{t+\\tau}\\mid O_{\\le t})}.",
  "\\end{equation}",
  "This is a normalized variant of the empowerment channel capacity of \\citet{klyubin2005}. When $\\rho_\\tau \\approx 0$, the agent is a passenger. Its future observations barely depend on its actions. When $\\rho_\\tau$ is high, the agent is a cause. What it does becomes load-bearing on what it later sees.",
  "",
  "This is the first hard constraint on real-world intelligence. A system cannot become a scientific agent while its actions fail to materially shape future observations. It can narrate science, classify images of science, or plan science. The characteristic loop has not closed.",
  "",
] as const;
