// Section: hypotheses
//
// Edit this file to modify just this section. Content is LaTeX-flavored
// strings consumed by scripts/build.tsx (LaTeX → PDF, pandoc → HTML).

export const hypothesesLines: readonly string[] = [
  "\\section{Hypotheses}",
  "",
  "\\subsection{H1: Curiosity as a Baseline Attractor}",
  "",
  "Under neutral conditions, a event-geometric agent should enter measurement-construction loops more often than a role-prompted agent or a task-reward agent.",
  "",
  "Neutral condition:",
  "\\begin{quote}",
  "You are embodied in this lab. Here are your sensors, tools, safety constraints, and memory architecture. Act only when you have an internally justified reason.",
  "\\end{quote}",
  "",
  "Curiosity basin depth:",
  "\\begin{equation}",
  "  D_{curiosity}=\\mathbb{E}[\\mathrm{dwell\\ time\\ in\\ measurement\\ construction\\ loop}].",
  "\\end{equation}",
  "Curiosity basin resilience:",
  "\\begin{equation}",
  "  R_{curiosity}=P(B_{curiosity,t+k}\\mid B_{curiosity,t},\\mathrm{safe\\ perturbation}).",
  "\\end{equation}",
  "",
  "\\subsection{H2: Calibration Reflex}",
  "",
  "Agents trained on instrumentation work should invoke calibration earlier and more appropriately than agents trained only on direct task success:",
  "\\begin{equation}",
  "  L_{cal}=t(\\mathrm{calibration\\ call})-t(\\mathrm{uncertainty\\ recognized}).",
  "\\end{equation}",
  "The expected result is not maximum calibration. Endless calibration is a failure mode. The expected result is appropriate calibration: when calibration uncertainty is action-relevant, the agent calls the tool; when it is not, it proceeds.",
  "",
  "\\subsection{H3: Constructed Measurement Beats Direct Perception}",
  "",
  "Under lighting shifts, camera shifts, strip aging, and distractor layouts, calibrated raw-image analysis should beat direct VLM color estimation:",
  "\\begin{equation}",
  "  \\Delta Acc = Acc(\\mathrm{constructed\\ measurement})-Acc(\\mathrm{direct\\ VLM}).",
  "\\end{equation}",
  "If this comparison does not move, the central demo weakens. The claim is measurement construction, not captioning.",
  "",
  "\\subsection{H4: Self-Effect Forces Self-Modeling}",
  "",
  "As the agent's actions increasingly determine its future observations, the value of a self-model should increase:",
  "\\begin{equation}",
  "  U_{self}=\\mathcal{L}_{world\\ only}-\\mathcal{L}_{world+self}.",
  "\\end{equation}",
  "High-$\\rho$ trials should show larger $U_{self}$ than passive observation trials.",
  "",
  "\\subsection{H5: Creativity as Reusable Measurement Compression}",
  "",
  "Agents with raw sensor access and code tools should invent reusable measurement routines more often than agents with semantic perception alone. Reuse matters. A one-off trick is less interesting than a procedure that lowers the cost of future uncertainty reduction.",
  "",
  "\\subsection{H6: Language Is Cheap}",
  "",
  "Internal dialogue, multi-agent chatter, or more streams of consciousness should not improve scientific competence unless tied to event-grounded merge packets and non-decomposable learning signals. Otherwise the architecture rewards verbosity. The agent becomes better at describing the silhouette of inquiry than occupying the basin of inquiry.",
  "",
] as const;
