// Section: the-event-stream-is-not-a-log
//
// Edit this file to modify just this section. Content is LaTeX-flavored
// strings consumed by scripts/build.tsx (LaTeX → PDF, pandoc → HTML).

export const theEventStreamIsNotALogLines: readonly string[] = [
  "\\section{The Event Stream Is Not a Log}",
  "",
  "Memory is too weak a word here. A log records what happened after it happened. An event stream is constitutive. It constrains what the agent can later infer, cite, replay, and become from.",
  "",
  "Every camera frame, motor command, observed pose, tool call, calibration update, hypothesis, posterior revision, model judgment, and training update is appended as a typed event:",
  "",
  "\\begin{lstlisting}",
  "event_id",
  "timestamp",
  "stream_id",
  "stream_type: sensory | motor | tool | calibration | thought | judge | train",
  "source",
  "payload_ref",
  "summary",
  "parent_event_ids",
  "causal_tags",
  "uncertainty",
  "calibration_state",
  "model_state_hash",
  "safety_state",
  "world_state_delta",
  "belief_delta",
  "self_model_delta",
  "training_candidates",
  "\\end{lstlisting}",
  "",
  "The event history is autobiography, audit trail, training corpus, and causal graph. A claim unsupported by event pointers remains narration, not knowledge.",
  "",
  "\\subsection{Streams}",
  "",
  "The event set is partitioned into typed streams:",
  "\\begin{equation}",
  "  \\E=\\{S^{vis},S^{motor},S^{tool},S^{cal},S^{thought},S^{judge},S^{train}\\}.",
  "\\end{equation}",
  "The state of the agent is a function of event history:",
  "\\begin{equation}",
  "  z_t=f_\\theta(e_{\\le t}).",
  "\\end{equation}",
  "The world model predicts future sensory events under candidate actions:",
  "\\begin{equation}",
  "  p_\\theta(e^{sens}_{t+1:t+k}\\mid e_{\\le t},a_{t:t+k}).",
  "\\end{equation}",
  "The self-model predicts the agent's own errors, latencies, calibration gaps, and action reliability:",
  "\\begin{equation}",
  "  p_\\phi(\\epsilon_t,\\kappa_t,\\tau_t,\\mathrm{failure}_t\\mid z_t,a_t).",
  "\\end{equation}",
  "This is the practical form of humility. The agent should not only model the world. It should model the shape of its own unreliability inside the world.",
  "",
  "\\subsection{Global Belief Ledger and Transient Streams}",
  "",
  "A single context window cannot carry this architecture. The cleaner structure has one persistent evidential stream and many bounded transient streams.",
  "",
  "Let $\\GL_t$ be the global belief ledger: the persistent narrative and evidential state of the system. It maintains active commitments, unresolved questions, long-horizon context, safety state, and global priors. It forks transient streams:",
  "\\begin{equation}",
  "  C_i=\\mathrm{fork}(\\GL_t,g_i,b_i),",
  "\\end{equation}",
  "where $g_i$ is a local goal and $b_i$ is a bounded context. Examples include workspace survey, camera calibration, pH-strip analysis, manipulation planning, safety audit, and sample classification.",
  "",
  "Each transient stream returns a merge packet:",
  "\\begin{lstlisting}",
  "merge_packet = {",
  "  claim,",
  "  evidence_event_ids,",
  "  confidence,",
  "  uncertainty_delta,",
  "  belief_delta,",
  "  proposed_next_actions,",
  "  unresolved_questions,",
  "  failure_modes,",
  "  training_candidates",
  "}",
  "\\end{lstlisting}",
  "",
  "The global stream updates by structured merge:",
  "\\begin{equation}",
  "  \\GL_{t+1}=\\mathrm{merge}(\\GL_t,m_1,\\ldots,m_n).",
  "\\end{equation}",
  "Raw rambling should not be merged. Evidence pointers, deltas, unresolved contradictions, and failure modes should. Premature coherence is one of the easiest ways for an agent to lie to itself.",
  "",
  "",
  "",
  "\\PaperFigure{event-agent}",
  "",
  "",
  "",
  "",
] as const;
